apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
    name: http-gateway
    namespace: kube-system
spec:
    gatewayClassName: cilium
    #  addresses:
    #    - type: IPAddress
    #      value: 1.2.3.4 #example
    addresses:
        - type: ENC[AES256_GCM,data:Rp7o9DtSge4Z,iv:F+RPbCGjY8CyOfeMaK4k1cSdxbOfP3kvTGHmi3Qc65U=,tag:ihvg3UHGsyyYnUFvOj4GYg==,type:str]
          value: ENC[AES256_GCM,data:ys1dWM4CHmsYJTy0QNQ=,iv:VFk2Y1Eha0R87jjLvAUJ5WswXLuu4+6c5oz0NDysxZQ=,tag:Q3+724e4t3j37/8AJ/Kklg==,type:str]
    listeners:
        - allowedRoutes:
            namespaces:
                from: Selector
                selector:
                    matchLabels:
                        http-gateway-access: "true"
          name: http
          port: 80
          protocol: HTTP
        - allowedRoutes:
            namespaces:
                from: Selector
                selector:
                    matchLabels:
                        http-gateway-access: "true"
          name: https
          port: 443
          protocol: HTTPS
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-01-31T00:15:00Z"
    mac: ENC[AES256_GCM,data:+XDYy8hdE1e2SHtBJqf/EqMINlkH2MsEf+YAMWUyne6QfYDXLxY6O3D9lXDnu6hfMKuAioCKznsb2nBkyhpXyKfI0xzHm263sePfmiDW54S8aY7ZegKpB15QbqVvHNcLE3uqauArfUHQvss64aQBq36dP8IUNYWKD2O7V5xLD3c=,iv:c93/yepAJRE09XQxWyTyEXpk1WKqZtvqWNT76mlov+A=,tag:9vtCyaitr8LjD357LvGH1Q==,type:str]
    pgp:
        - created_at: "2025-01-31T00:15:00Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA262vqLG74HEAQ/9EBYPSUg8N6jAlQPPgfLs0ri+XJZpGlSdzsjsTSUaG2Ji
            nlvfzlz9KbrqTFvi1mOnP9QeGRJCXxsOXBXn9adhZlGCVX4uOnnzEzf3okf2a/sS
            3Pg3OcvwDS+ADBtX9lQD9olx5dObAnP0nqd+cNaGOLtdXKWN6xoIre3eR01JK/Gx
            Qcknxmt4SDQZAiFjLVz2E/LSgJ077BMjA8V5LiMhUyYR9KJEvN/nsS4yDjiK21Qt
            3ATLtA60Ae3C3YVB0MCnZKwhKA2xL8JbT0AxV3YHTb7pr4WRVXldm6v3R4NsEtxh
            Kr3pCFSAf/mO6EYURDCgPc4sYyCaVG5YTPiAs7US6X6k9aYHoYJKT6ZWLMjOEMU/
            Uv9skvSPOmP1spDpi4xoG5Narg3+qdMIneZAtDIySdlO2XKEyDdAB4CZ/8zw+f5U
            lembN3KEupOEzt0UV1zsIYhq11aGB6N2q4WFOxT2kamajvRseogm7ym002EBHHDk
            bdA5Uj8jM7uSz8oUqHNqU76sZ6E/OvQWdlb/spIn73yz7jt5qXGqS7dtm7h9JDUR
            nqF8XbGrv285a7BwK8SZZIrA98wwVAPXa+hsgSMWbioEILCcAHVuF+26M2x8NbXc
            6fXlWUPhZgiXCVecdC/kDY9bweMjT07d1sA2mI6UqpsOd73AzDh9kHLbmHvkeozU
            aAEJAhBrw9iaeZ6PewdadhyA4TMQlfEpPeCxTRfRSH8dONuqU+BRLwQpJiVY94lf
            I45wsmfA7QrVkWYNgGFIMTdYkAXdx1+vsZYkE2n2GXxd7Dj+6IzGvp1mZaZxwWwz
            TqE+e2i7BeW5
            =+Hw2
            -----END PGP MESSAGE-----
          fp: 75305C71C2CBD1BB31E45BC9EB711729A929833C
    encrypted_regex: ^(addresses)$
    version: 3.9.1
