creation_rules:
 - encrypted_regex: '^(data|stringData|caBundle)$'
   path_regex: 'bootstrap/config/.*\.sops\.ya?ml$'
   pgp: 75305C71C2CBD1BB31E45BC9EB711729A929833C
 - path_regex: cilium/gateway-http.yaml
   encrypted_regex: ^(certificateRefs|addresses)$ 
   pgp: 75305C71C2CBD1BB31E45BC9EB711729A929833C

 - path_regex: podinfo/https-route.yaml
   encrypted_regex: hostnames
   pgp: 75305C71C2CBD1BB31E45BC9EB711729A929833C
 - path_regex: podinfo/https-route.yaml
   encrypted_regex: hostnames
   pgp: 75305C71C2CBD1BB31E45BC9EB711729A929833C
 - path_regex: podinfo/http-filter-redirect.yaml
   encrypted_regex: hostnames
   pgp: 75305C71C2CBD1BB31E45BC9EB711729A929833C

 - path_regex: cert-manager/controller/protected-helmrelease-cert-manager.yaml
   encrypted_regex: values
   pgp: 75305C71C2CBD1BB31E45BC9EB711729A929833C

 - path_regex: cnpg/configmap-helm-values.yaml 
   encrypted_regex: values.yaml
   pgp: 75305c71c2cbd1bb31e45bc9eb711729a929833c

 - path_regex: victoria-metrics/configmap-helm-values.yaml 
   encrypted_regex: values.yaml
   pgp: 75305c71c2cbd1bb31e45bc9eb711729a929833c
