apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Use a specific version instead 'latest' if you want to install a specific version
  - https://raw.githubusercontent.com/rancher/local-path-provisioner/v0.0.31/deploy/local-path-storage.yaml
