apiVersion: v1
stringData:
  PAPERLESS_SECRET_KEY: ${PAPERLESS_SECRET_KEY}
  PAPERLESS_ADMIN_USER: ${PAPERLESS_USER}
  PAPERLESS_ADMIN_PASSWORD: ${PAPERLESS_PASS}
kind: Secret
metadata:
    name: paperless-secret
    namespace: paperless
type: kubernetes.io/basic-auth
