apiVersion: v1
kind: ConfigMap
metadata:
    creationTimestamp: null
    name: authentik-helm-values
    namespace: authentik
data:
    values.yaml: |-
        authentik:
          secret_key: ${AUTHENTIK_SECRET_KEY} 
          error_reporting:
            enabled: false
          postgresql:
            password: ${AUTHENTIK_PG_PASSWORD}
        
        server:
          replicas: 1

        postgresql:
          image:
            repository: bitnamilegacy/postgresql
            tag: 15.8.0-debian-12-r18
          enabled: true
          auth:
            password: ${AUTHENTIK_PG_PASSWORD} 

        redis:
          #image:
          #  repository: redis 
          #  tag: 8.2.5-bookworm
          enabled: true
        # clusterRole:
        #     enabled: true

        global:
          security:
            allowInsecureImages: true
          postgresql:
            auth:
              password: ${AUTHENTIK_PG_PASSWORD}
