apiVersion: v1
stringData:
    DB_USERNAME: "authentik"
    DB_DATABASE_NAME: "authentik"
    DB_PASSWORD: ${AUTHENTIK_PG_PASSWORD}
    username: "authentik"
    password: ${AUTHENTIK_PG_PASSWORD}
kind: Secret
metadata:
    name: authentik-postgres-user
    namespace: authentik
type: kubernetes.io/basic-auth
