apiVersion: v1
kind: ConfigMap
metadata:
    creationTimestamp: null
    name: immich-helm-values
    namespace: immich
data:
    values.yaml: ENC[AES256_GCM,data:nAABZg6nJ8+AlxYgu28umM8Y2x7WhZ5mhVd2Vmai7d0HeIAatw8gOsXQArWZ8JK6SKcZpG2Enp+174oGLicHwgvbs/Ze8XEKxLKTKywbGqayJbvx0EL6GRmFdfxE/ni9nC7HIziWKboDfE6UwM2X3pzh5T/hJaPEkirH25rOldtDz7PadtXtapd49eeVeg3/hyLQNSv6/U/eRbqdDu4yMgMFlr6dh/z8baPh6CWrn77cSiR4WX9EtkDnX6uGTm99a0BzRQd+aK3aJVrb9W1ANDKah7D+knDTaA7lHbYhg9H2LGr8CsOze902EylakoCu7vA28ZcfeIPHfaMi08Ye2Ql3uYcVOs5MEUdHtqCF60IA6lf9t8uUDq0N1C0ROC8v2kqYhb3Idhjcl0uaX8MIIjvylbQ9kVBGaWXr3aa9sQ1NEo2vgRTOxsNQ5+o6OjvOnyWbthR7onHWM86I2eHf7wX1yQA6osrUBX5nNslIW3rvFBCGedML+NoIPSz0UItFQnek/A/Veuy2y0Q8xfRlyB2n+fIvAvpX+P1VxS/SzXH5Sm7ola5vexro/pE/hjBry4d/sBnBFXXRY8o6RFYx4d4D/ukzIvF2RA/hii7MSyDpni9JU2iY/FnrB1QUq0n2EAvkvZOy9qIQ2QxaihqcYxYf1/iyAZ/lKQF5hUGGwTxp2zLpz99F09W3w5gwPd5y2zqou56Jp7x34//jLNkUAzvyGtJOBkgxlHulAG8IfiJyFWkk0txmf3Z5fG81dojrRPZQ1Pd8I7HdZ4iEfCVWA4zd+Go1b0IWXtZPOxa2FFfdwHHnJ9QfvgTdpWTz0XnEyeMa+vzo4pZ9s/ZTjCfP9A3UOIevF0f07Xvow1p2fBdSPWsx051C2t5DnC5jyDmkBD2xx6b8FDm8BharvQvZx6KdMCpSI/xZx2V7lTydhYiEeibBVz5AYFx2uZL1Y1CHqpzh8j/FifkNJXG//w8t0r/3MbMSS1MViric6azumw0cmYdScJ5A7uIQvbGud77q3Obl39uq6R7YVZoHlqOzo0yHMKCa/LVsEgOhNgKWKtks3KGFCFU4Q6drZVl0jKZbIPm8TnZOmD+I8vppctIjLMMPaAyvXDjV/K0TRjjEZSZlj4MlISwvOP2xw1NMjQKdJSW46Z6w5BHguk4J9Z6WhCnUyAAx2Hzk5Mj8wor5pXjVuDmhaCQpaXCR6qkiYnLyVUWPg1gAs879cHYs+0n7jm9wRQE37CLZxeCyzAy2vTcY2yu5wJkkl+D3cA8cap0aAkaYmMDfpZH5Bed26LbcfsYUYo7rpsEWkfF28N4LhXeNQ6Tcg3nNDy1/pRDQdU0aG/jY1GZZ9DAbmViceYimTRXpPZZhRcJJkDW97avfKfuxzW6ThOMPMbe/mTElXMQUyWteAjQ+yim+6BCHz8KjlSLD7Cr7Cv+AQEFR/24QcY6maaL8dDwXSmfq78jzPbp/BArnYzHn9mDbsRIhLZHMUAyz8VMNGaBBwR4J2+ZatljfgND7gtn3ajp/itzsUY/yJOS9xo76oH56TCsM2QGm6NoWBvYU9KKw0uJFZ2pB8RLko2XReWorLLfIZVeQZvzfGVgWTOFfUZxTRg1//mjG4j+b6Dbj1eSVkXKvMCfzw11yT7a2mVOsCBkI7WlO5+gYfg5zWqFTekqL9IDee1+FMtOUwyUITmPd/68r0jKn8S/KMFR6dRfrSLT5FmCxfiQeGmbuKSsuVkiDr77gHseesFJSh/mCdqzXXXa/hLOAKQ3r+Tazl8lxbPA46kXMdNsCm9qDFr2Ho801AykgH8IDkaVaA5EflEIPDjjAC5jgzHscjGxhih65NER7URHc/vL6PUFgeDa2tqJM47fext+JVP2medrmFgkkUDiEZWLFBkK+4gc90mEgU54099wP9OEBrh3bCzwtKkI6lBc6ldY1n12AJiGfuRg/k/y4zTxbhq3pTH7bQCqBJ7yFY0NhUCfzy4fi2ztRpn8A8t6eQHDNTOUsblES+2RBqUrp6iKs0NP3jZHnqS4dl3GPxICXCI99mYhrAE1ShJHHGvvs+qSPdqI3iknJWFETMRQdeCKg7kTx1O+sdECIpvJZBAiagMzlsWfhHJ3/QWp2v1+21YffieHbjgxQ7kaV8BywtXrhhWnyTe6owJXzJBcH7pIn9DslNIbHBKwVj5S7s9bjBiPDKVUmPIpxvH2F7+X5y/Uu3tjTiN7ViSHv3T2GzhO0ZuFZp/gImseEFyF703sj7w0G6S927SEemSj6fucx+gq3vhID+ojWKynSgtrE2mIYdkMgPS9VFFrXc3/BnRlkuMazQYYFB6TeolT9G9eB/CMs9dh19LoIBtZaJq6FqSHgaKmxpurBDFHayjf3+FekCuyv8uXXBU7lpFl62mM1YYEoSkYZ2RmJHN2vAnGWRMPbNFEsHLleIhXb1wgEaCvf1Zk8UooMX84G5MWCEv7bdWbIQkXc1FEL94erYXMkD349nqzNZSXgJSUMNkPZh1sB7DrfTG4JtmkYMhG9KzaGysXn5n7GhijO1Gr0vo7PjQu1v+kZIqSfv4dZqU3HSCuqiT//Ne7EFtEQMbdlqC/dm5jXWVRFB2Jf2bBMssm1VXbVdZJeS5AnPMSGtXF6zWrgVOjvaAVehwvN5cV8o+aM7Ghlmw22aiODTIA2z9J2dKiWkQawwdzHG0WGraLcUrumb+xGETgLzOxJMuQ+JkA9N/RrRR5GfDYuFCWzISzNEo+nMeBXAp2TDtMoU/EbjMFbD9XxPJgT7gtR5R+TKADifXJ/RyE/oUeu0fd6qwRQjxn0hmR1pQfAOwFg6gJsKq6poFqwcw0/xN2+ETvULIHAiSQM0mWSn8qVY6f1oLN5q2m1JJ7sJuHAcPRoJ/YdbRZ2uWT8yS4dD8ZHgA==,iv:SHAeqKuxilroENZlqoOfwyc0vyM9LcW1cCBiUAfQaJ8=,tag:Yx5a3TSKj1mzXP7K3MaTkQ==,type:str]
status:
    conditions:
        - lastTransitionTime: "2025-02-07T00:14:49Z"
          message: Running 'install' action with timeout of 5m0s
          observedGeneration: 2
          reason: Progressing
          status: "True"
          type: Reconciling
        - lastTransitionTime: "2025-02-07T00:14:49Z"
          message: 'Helm install failed for release immich/immich with chart immich@0.8.5: execution error at (immich/templates/checks.yaml:1:64): .Values.immich.persistence.library.existingClaim is required.'
          observedGeneration: 2
          reason: InstallFailed
          status: "False"
          type: Ready
        - lastTransitionTime: "2025-02-06T23:42:36Z"
          message: 'Helm install failed for release immich/immich with chart immich@0.8.5: execution error at (immich/templates/checks.yaml:1:64): .Values.immich.persistence.library.existingClaim is required.'
          observedGeneration: 2
          reason: InstallFailed
          status: "False"
          type: Released
    failures: 1
    helmChart: flux-system/immich-immich
    lastAttemptedConfigDigest: sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
    lastAttemptedGeneration: 2
    lastAttemptedReleaseAction: install
    lastAttemptedRevision: 0.8.5
    observedGeneration: -1
    storageNamespace: immich
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-03-04T07:11:21Z"
    mac: ENC[AES256_GCM,data:g4ZqjWYivsY9zly0DfdNCF+j7Cu2T1+8lzu9Y9q+EyJjuXYicjIpsZWeLvfdksuxr/Icfs73l0UIBCF4PruH5DykLkORjuwh5mN/qTfVBS5LauXV5PXqBXhxFqDThDsbXXoqrB8VWnszAY6n29jhTNme3TGGrDaimjT5p+nI300=,iv:ydqvmgmdO6VnrG6Gx7kYLcTxmVotzZ05hLrPJa1vxhM=,tag:VDU3Wr3R6j2OUsF9kM9Kkw==,type:str]
    pgp:
        - created_at: "2025-02-07T00:34:31Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA262vqLG74HEARAAqjn9qhnzNmIHL07f2Ncuyqw11Wh9alqDM7nT2Y5uEW1a
            OfGVEjJXytv6ioS5zYpElsPbmRMhaOv4F2tNy3ECzuQtwJiDiaA59MmGg4bcvXvP
            /rFPpc0aP7qJxGEomOUI9H8+LBUKLSZUlTkMQvDRpI0CX7QTLy8K+Ozvkr5pBnO1
            pkpLw1m0AUn4wd80/4TmmWDYNeMVWLpxWZ+xmuGRwBZmiPsmH2UfeYNv6A7ViXDf
            WSGWIg3CM2SGNnf8dIHkcHwNFremzYQ8v+nGb7rnrAA4ydag7gG8iw22xllgaCoA
            dkUzkc8gqVFztDIizNs0RXp3/h6OjaSUtSv1hBM9ovmRbC1LLoyfSA71d2CUByPl
            V9tU7jIKJ0kmhHTcoCGfPOi+e8OCwbg7TXRna+a9dUsVfBUZgf9qj8JopJQMUAP7
            0c1WwvJi4OMEqXvzBWz5OVdiZhRViCO4OZ2l3ZuqRGRahmTYlAo6coxO7wq3OsQ9
            CcHjlAGEUreqylHdGsylvjixyhQmKt6ZBlsW1CkiAetJQ6BmKF6ZfKkapQgmKUtz
            Qjt1AlosjNn6sUTEpRd/DpXsF3X7GIkgKbsebSONEnhkFCcpg/i03hMbgxAdT/LB
            2qrXEGS0F9wGAJ/N9oEArKxZ9g5i+FyTjaOYqCqUnEBN7KhCWOyxptRf3WPE0gPU
            aAEJAhB2ULNlkHaFEW+hObmU6MF2GosIabuErFZrPhUn+K4gI+heXsIB/kdqopwY
            x7lIw1Fy9CFTVQPkkcxO/v06i3wB0/xpFZC5fx3jJRZX8OB2BiE9DGjkD4uZ8eM8
            RdmKZz9mm5oU
            =Wpp2
            -----END PGP MESSAGE-----
          fp: 75305C71C2CBD1BB31E45BC9EB711729A929833C
    encrypted_regex: values.yaml
    version: 3.9.1
