# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: immich
    namespace: immich
spec:
    chart:
        spec:
            chart: immich
            reconcileStrategy: ChartVersion
            sourceRef:
                kind: HelmRepository
                name: immich
                namespace: flux-system
            version: 0.9.0
    interval: 15m
    releaseName: immich
    timeout: 5m
    valuesFrom:
       - kind: ConfigMap
         name: immich-helm-values  
         valuesKey: values.yaml # This is the default, but best to be explicit for clarity
    
