apiVersion: v1
kind: PersistentVolume
metadata:
    name: immich-static-library-pv
spec:
    capacity:
        storage: 300Gi
    volumeMode: Filesystem
    accessModes:
        - ReadWriteMany
    persistentVolumeReclaimPolicy: Retain
    storageClassName: local-path
    local:
        path: ${IMMICH_DATA_PREFIX_PATH}/static-library
    nodeAffinity:
        required:
            nodeSelectorTerms:
                - matchExpressions:
                    - key: kubernetes.io/hostname
                      operator: In
                      values:
                        - ${IMMICH_K8S_DATA_NODE}
