apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: immich-static-library-pvc
    namespace: immich
spec:
    volumeName: immich-static-library-pv
    storageClassName: local-path
    accessModes:
        - ReadWriteMany
    resources:
        requests:
            storage: 300Gi
