apiVersion: v1
stringData:
    DB_USERNAME: ENC[AES256_GCM,data:b1vRHFxC,iv:KqrnQF+umkQ+xdoqBUPNF+kZFDJ25gE2Lzu9aceJpNM=,tag:OqzEawRsTfAohddwhctCwQ==,type:str]
    DB_DATABASE_NAME: ENC[AES256_GCM,data:IGQfVN8r,iv:ewtKZ3f35hmzOqX9ysKDJz2ZT3GHJtBVWoG3DOWGL3k=,tag:pdjFpupCvz6N5wW5Qjbtaw==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:UZgW0ZZHMbJi10HAaISc9Hp4Xnw=,iv:J2WDYoGK7Ywck2ycq5PFwfC51MLWRL3dm0FalgUDEXM=,tag:OMMZLb4OLZR4w3d6Q/UGOw==,type:str]
    username: ENC[AES256_GCM,data:pl2ddxPa,iv:3GxfDoZJhBuZk5GowzHGYaskEcYh8GFT/Fwd3b1jPp4=,tag:CfWkz1QjPRrmzX2BpzKcUQ==,type:str]
    password: ENC[AES256_GCM,data:J6pHl1Wy7t+AeqIYj9zSh26WQpY=,iv:ODlTq4VG3BZUFhhhc02M8rpbI8qqKuucD9TO3QTTtuo=,tag:8eO702a8kvAgf8L6/CCD5Q==,type:str]
kind: Secret
metadata:
    name: immich-postgres-user
    namespace: immich
type: kubernetes.io/basic-auth
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-02-07T13:02:30Z"
    mac: ENC[AES256_GCM,data:FnH3sISilbnOhAz2reX9AVwXHijMu0R4dm3ZuqAMps8hUP/Ltmcm/C+ni2QFMiCgW8DEsNscJZatxYdcYgevZmz9SngbbG0BrwJS97sDpZeZiNj7Q9/onpQA0plZCoJPqxSXr7jPl8IWrJIFWk0QskhX0nWXMS61YuL5nkzxKX4=,iv:1Pbe9VJjAtrNNKanJZpJ+p7iDHvjws9aqU7VqpMNNLo=,tag:fY/uaSWAnhEei7bOxlkKvA==,type:str]
    pgp:
        - created_at: "2025-02-07T12:45:14Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA262vqLG74HEAQ/+Nm2nGSLG+/jk8QaT7oPPCQRTROeTP9ESHbhgl6xOwUwK
            EZx2Z9JT/kXjGfvwBVqUZVrfCaLgQQlfXpp34+qypZfk2BmKHzUwCQ0GGiwUS57i
            cWY2xYGcg6cA+ZTu9e0/BwZ8D89lceQ2YxIF/fyFNwsxrERAYwjFBCUc37amUORZ
            qeuHxUcAfNUDmTLdMtnF0f47LMU+zcYcQ0mpiqwc/nwaUg/yXDOGo8RtRecxRuzZ
            fnEdsisEkKIgRwD3Ypf45n2vPD7uUQo9ELklhAO1Gi0BDq8RD+hN3b8JuM8Cb75W
            xuGMwB2HhrFFzB67DexgS3uGw9mdCgoVonpVQ6Kv8RH8dRXWROZE31QBIxO7vI6+
            Mo88HP5i/F3nE2LlIt8+ye+8WK4rjwQGn5QVEkIOA+boPHyLXUBAMRxH3nM/WZBy
            GS9hUFeKfGm4jTWK1xF+NT8PaLvKlpMJkW1FFKHHnDYrJBWExd2/dxlWL3Hz0064
            JOH2jCi6t0PbW2VQU3cazuOkkw5L18pMnNZjSjkiEJn1fe/5ZX6ufxVb8mMUAaEP
            L1vd0qC7yRr2Ic3vma3cvr/hpyuslo9V5RgWLJCM5SscPgjiCIpZEaxxY1StA4Vb
            I5Houh7ka5rz0iW+td6lgzONgXNHUHO26oB+A8MeKBuCa8kuaGnlJJEQkqUusCDU
            aAEJAhBt32B4rxvN/bgEnuzQrSNq7VqJsgr3K4fn01A1tZx/EzVru57S1/wFH8Bq
            49QNNhluOqiG6BCsivlgva9jDYdipc9la/EKKel8WJxPZ+fk7M2oD/lpbnaGjZu+
            gpxd+Tn9eaeC
            =MBJN
            -----END PGP MESSAGE-----
          fp: 75305c71c2cbd1bb31e45bc9eb711729a929833c
    encrypted_regex: stringData
    version: 3.9.1
