apiVersion: v1
stringData:
    DB_USERNAME: ${IMMICH_DB_USER}
    DB_DATABASE_NAME: ${IMMICH_DB_NAME}
    DB_PASSWORD: ${IMMICH_DB_PASSWORD}
    username: ${IMMICH_DB_USER}
    password: ${IMMICH_DB_PASSWORD}
kind: Secret
metadata:
    name: immich-postgres-user
    namespace: immich
type: kubernetes.io/basic-auth
