kubeProxyReplacement: true
k8sServiceHost: 127.0.0.1
k8sServicePort: 6443
operator:
  replicas: 1
externalIPs:
  enabled: true
nodeIPAM:
  enabled: true
hubble:
  enabled: true
  relay:
    enabled: true
  ui:
    enable: true
l7Proxy: true
loadBalancer:
  l7:
    backend: envoy
gatewayAPI:
  enabled: true
  gatewayClass:
    create: "true"
  hostNetwork:
    enabled: true
securityContext:
  privileged: true
#  capabilities:
#    ciliumAgent:
#    # Add NET_BIND_SERVICE to the list (keep the others!)
#    - NET_BIND_SERVICE
#nodes:
#  matchLabels:
#    kubernetes.io/os: linux
envoyConfig:
  enabled: true
envoy:
  enabled: true
  securityContext:
    capabilities:
      keepCapNetBindService: true
      envoy:
      # Add NET_BIND_SERVICE to the list (keep the others!)
      - NET_BIND_SERVICE
      - NET_ADMIN
      - SYS_ADMIN
