apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: victoria-metrics
    namespace: victoria-metrics
spec:
    chart:
        spec:
            chart: victoria-metrics-cluster
            reconcileStrategy: ChartVersion
            sourceRef:
                kind: HelmRepository
                name: vm
                namespace: flux-system
            version: 0.17.6
    interval: 15m
    releaseName: victoria-metrics
    timeout: 5m
    valuesFrom:
       - kind: ConfigMap
         name: victoria-metrics-helm-values  
         valuesKey: values.yaml # This is the default, but best to be explicit for clarity
    

