apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: cnpg
    namespace: cnpg
spec:
    chart:
        spec:
            chart: cloudnative-pg
            reconcileStrategy: ChartVersion
            sourceRef:
                kind: HelmRepository
                name: cloudnative-pg
                namespace: flux-system
            version: 0.23.2
    interval: 15m
    releaseName: cnpg
    timeout: 5m
    valuesFrom:
       - kind: ConfigMap
         name: cnpg-helm-values  
         valuesKey: values.yaml # This is the default, but best to be explicit for clarity
    

