apiVersion: v1
kind: PersistentVolume
metadata:
    name: bind-data-pv
spec:
    capacity:
        storage: 1Gi
    volumeMode: Filesystem
    accessModes:
        - ReadWriteMany
    persistentVolumeReclaimPolicy: Retain
    storageClassName: local-path
    local:
        path: ${BIND_DATA_PATH}/immich
    nodeAffinity:
        required:
            nodeSelectorTerms:
                - matchExpressions:
                    - key: kubernetes.io/hostname
                      operator: In
                      values:
                        - ${BIND_K8S_DATA_NODE}
