apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
    name: https-route
    namespace: podinfo
spec:
    #  hostnames:
    #  - example.com
    hostnames:
        - podinfo.${SECRET_DOMAIN_0}
    parentRefs:
        - name: http-gateway
          sectionName: https
          namespace: kube-system
    rules:
        - backendRefs:
            - name: podinfo
              port: 9898
