apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  chart:
    spec:
      chart: cert-manager
#      version: v1.15.4
      version: v1.16.2
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: flux-system
  interval: 15m
  timeout: 5m
  releaseName: cert-manager
#  valuesFrom:
#  - kind: Secret
#    name: cert-manager-helm-chart-value-overrides
    # valuesKey: values.yaml # This is the default, but best to be explicit for clarity
