apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
    name: letsencrypt
    # name: letsencrypt-staging
spec:
    acme:
        server: ENC[AES256_GCM,data:GRdyCDwgU5qVn5Iht4pm2J21pJ0PJixW8vJrKu5RmFURva5DTEW6MYfaU+3oFw==,iv:NFeSYox6oflI8npjilAi06lHiVVUpuPA6ggSF1EqLuY=,tag:eV8m1n+9QrUgCBj1DMzftw==,type:str]
        #ENC[AES256_GCM,data:sVL+NYXfGpMIGL4Y7ZYs+R/646Q5LkHxDsbVbsq4MUAy8mdj6KBNJLTNxPLDMQIfRvyhxc6A6A7KBBbMyyKR,iv:FL0TrVN9+CBGMToxIO7786kbgxZ5M/6H2g+8T1s87Z8=,tag:pmuWwCVMBqvYy3gagUHpVA==,type:comment]
        email: ENC[AES256_GCM,data:AyXT07mdBQs2P+rEjl7r4nnpaEA=,iv:lGjlvuWiY5YA4jYPrYTjtkDWRX5OSGjP9t54SF4bso0=,tag:IN2LH29rcAFy4KXmeZJAHg==,type:str]
        privateKeySecretRef:
            name: ENC[AES256_GCM,data:hTrE0yUajOWSoMhLaoSx5B5WfCNOB8+UcRSuSjKP9La4M8E=,iv:iQFh7Dyv24xjG0Sk62BAsXXnPPFex+r38M0MmkWAUWA=,tag:qLtF11fPpwGCy5x+2o4zbQ==,type:str]
        solvers:
            - dns01:
                rfc2136:
                    nameserver: ENC[AES256_GCM,data:/sYo6R06lMys5ogBETcqPQ==,iv:1ivZZK1nxWVHoBhq2oJN3ZEL1cPYctkkc5CS4QPhoqs=,tag:anWYI6+6Ztcwtdak1QtVZg==,type:str]
                    tsigKeyName: ENC[AES256_GCM,data:JNe++847B/8=,iv:gd31viqozE4o6m+SNKXgAzTUwUTLgelWPa+gPqkiE+M=,tag:gOTrtgu9mJ4A6JnMXbV48Q==,type:str]
                    tsigAlgorithm: ENC[AES256_GCM,data:D9v67nikmcAyUw==,iv:UX6o5Qx/d0HNIkKKoSkAKSL/Ijxq95+Wb1t1gTc6TQw=,tag:JWtP1kn0GfqVpr76y2kiFQ==,type:str]
                    tsigSecretSecretRef:
                        name: ENC[AES256_GCM,data:cuqAiA==,iv:qHonK05VhRGoJD53BhY272VJmC3mQz3yiTZ7bFxvFBQ=,tag:yO5ZkQqXBBme9Y3+DtApvA==,type:str]
                        key: ENC[AES256_GCM,data:BTmjnv4jDg==,iv:dWksah/9ozCXalX9KocAMY5WbkN/QAVxpvOIdIeuC1I=,tag:bIhQcmNx/VdyL9q9iMjNfw==,type:str]
                        #ENC[AES256_GCM,data:8D7KTdixe0lsOQ==,iv:ciPCo8rTZDQ/h6YKWmd0hM6e12X41HAJa2EpRgDoS0g=,tag:hCy5KPN6MTH86hkoN9EErg==,type:comment]
                        #ENC[AES256_GCM,data:ZYyG+k92wOUF8Ppfgg==,iv:3DdFNGP6T/+9SeA4i8ALW/pQGM3BuEKy2xZknKpbdtc=,tag:dwx8yKMhmllgjSic2TXWQA==,type:comment]
                        #ENC[AES256_GCM,data:7sLAj1HhR8Hei6wvdZyqRH2iuwiKUMBSVP9gFCf1yec=,iv:dGcdXOdPul71c6rRtZdMkXlfRINN+m7IyNWTWB/+Z2o=,tag:uawn43xxVQYbULAF3kenxQ==,type:comment]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-01-04T00:21:55Z"
    mac: ENC[AES256_GCM,data:DxO6ErFG9EMcsbO1M1i4Lv5itMrqS7uIc+qjjX/rtGIUWaBMGfmuovaixF3lrRalWntV/IzMffRxty8J2+CzW0+7yV7QpZPXKNySW2d5/fZycHA6yvMOqpYLRU4K96mRoVt7MmfxSw1zzIA7YThyeoP18SDleBgvrhL3b1nEJYw=,iv:+mT/pS+QAo3dMluLjrlbhA+owmER4knIzqg/t7pjl98=,tag:e23207pVai47q0WhgpdDgQ==,type:str]
    pgp:
        - created_at: "2025-01-04T00:21:55Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA262vqLG74HEAQ//U5UyOAMyR2REUsTmdfzkswhCiYYnHMf0Gh+BWyj0Iyhj
            jCbpYikZQBmH5q5DtuJN/7oqbNq9RBh3jaLpV+i6eIAtFAmtDj8IfpQFFDOerNHb
            XDMWyBuziIk32bawweY3QG+xWTRVE9EzauR4KCs7JjpEE7oJIF36CcU3EalH6SU3
            pK9mHqjWjhbD3SMcc0d1hWGIPFQrDk6KKkwFwVicuchGfpzlSix1bQWsJvMuXDv1
            Ih6QtbJK70alXLeumzNGOQbENmupbY8Xf8/GGXvfhOf7BVHwG0BKBnjL9QBOBgCa
            iY1LbBIi7HgRhG02ZxwI/wS1W7CvV/2mF2/SK4kA2ebQgqvNofeaGBM+l8x2Y1XJ
            +rkcpGP1hJDs8ghpSSO1QNlFEgz4U1d6inBLIfRPXnn2HoLMhXSqy1LIjmeMYIzK
            /Itbiti7mQY/SfO4+575NOam/ZbbqU2lFT521h5HMOvtPCZzDW4/ZmFZ1Sj2Cjr/
            h+pi8JvyFNnUPYxnbppoRNK5M+Vc2GVtlYYhj4z4BMVsBkHu/UMcLp87NzTLCkO+
            ndMb/ZMattGRuOW2ju+lL2ji2INHTBdCNr0n5uczOCDBjBG6uf0MGFOpANNEGUu4
            C8RErHQXDlK1Tp2b21Qd2ejT/bjNlSCdUGysvCeG8CVS5wXJmfN0e88JSUACmWrU
            aAEJAhApyQrRON2lp8uzzpA+Kkwoj71FjB3QeXMNlqyy7jamJA+vvC7spdPjpesU
            lW1aJvHwkFeyU+niYKSbtgyEmOtcmoWTiUu9Nwh15XJODJirfCW/b5PSjBtRFKo4
            E221WJwJTHIg
            =DXAw
            -----END PGP MESSAGE-----
          fp: 75305C71C2CBD1BB31E45BC9EB711729A929833C
    encrypted_regex: ^(data|stringData|spec)$
    version: 3.9.1
---
apiVersion: v1
kind: Secret
metadata:
    name: tsig
    namespace: cert-manager
data:
    tsigKey: ENC[AES256_GCM,data:gFG7K1tz/6G3/3a2nm7na0GNkRDTtqgNU6B+XAl0IqlewgrXKYlK924fmMU07iINdu4XVUu9ljJle+uu,iv:2EKHKNRN5Lh5DOgiP0Y0VVws5r6mpfgRnA549TyG/Dk=,tag:iXai2tB774WBcrdOAa8gPQ==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-01-04T00:21:55Z"
    mac: ENC[AES256_GCM,data:DxO6ErFG9EMcsbO1M1i4Lv5itMrqS7uIc+qjjX/rtGIUWaBMGfmuovaixF3lrRalWntV/IzMffRxty8J2+CzW0+7yV7QpZPXKNySW2d5/fZycHA6yvMOqpYLRU4K96mRoVt7MmfxSw1zzIA7YThyeoP18SDleBgvrhL3b1nEJYw=,iv:+mT/pS+QAo3dMluLjrlbhA+owmER4knIzqg/t7pjl98=,tag:e23207pVai47q0WhgpdDgQ==,type:str]
    pgp:
        - created_at: "2025-01-04T00:21:55Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA262vqLG74HEAQ//U5UyOAMyR2REUsTmdfzkswhCiYYnHMf0Gh+BWyj0Iyhj
            jCbpYikZQBmH5q5DtuJN/7oqbNq9RBh3jaLpV+i6eIAtFAmtDj8IfpQFFDOerNHb
            XDMWyBuziIk32bawweY3QG+xWTRVE9EzauR4KCs7JjpEE7oJIF36CcU3EalH6SU3
            pK9mHqjWjhbD3SMcc0d1hWGIPFQrDk6KKkwFwVicuchGfpzlSix1bQWsJvMuXDv1
            Ih6QtbJK70alXLeumzNGOQbENmupbY8Xf8/GGXvfhOf7BVHwG0BKBnjL9QBOBgCa
            iY1LbBIi7HgRhG02ZxwI/wS1W7CvV/2mF2/SK4kA2ebQgqvNofeaGBM+l8x2Y1XJ
            +rkcpGP1hJDs8ghpSSO1QNlFEgz4U1d6inBLIfRPXnn2HoLMhXSqy1LIjmeMYIzK
            /Itbiti7mQY/SfO4+575NOam/ZbbqU2lFT521h5HMOvtPCZzDW4/ZmFZ1Sj2Cjr/
            h+pi8JvyFNnUPYxnbppoRNK5M+Vc2GVtlYYhj4z4BMVsBkHu/UMcLp87NzTLCkO+
            ndMb/ZMattGRuOW2ju+lL2ji2INHTBdCNr0n5uczOCDBjBG6uf0MGFOpANNEGUu4
            C8RErHQXDlK1Tp2b21Qd2ejT/bjNlSCdUGysvCeG8CVS5wXJmfN0e88JSUACmWrU
            aAEJAhApyQrRON2lp8uzzpA+Kkwoj71FjB3QeXMNlqyy7jamJA+vvC7spdPjpesU
            lW1aJvHwkFeyU+niYKSbtgyEmOtcmoWTiUu9Nwh15XJODJirfCW/b5PSjBtRFKo4
            E221WJwJTHIg
            =DXAw
            -----END PGP MESSAGE-----
          fp: 75305C71C2CBD1BB31E45BC9EB711729A929833C
    encrypted_regex: ^(data|stringData|spec)$
    version: 3.9.1
